version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: hoodmane/pyodide-env:18
  environment:
    - EMSDK_NUM_CORES: 3
      EMCC_CORES: 3

jobs:
  # lint:
  #   <<: *defaults
  #   resource_class: small
  #   steps:
  #     - checkout

  #     - run:
  #         name: lint
  #         command: make lint


  install-emsdk:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install emsdk
          no_output_timeout: 1200
          command: |
            git clone https://github.com/emscripten-core/emsdk.git --depth=1
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest

      - persist_to_workspace:
          root: .
          paths:
            - .

  test-node:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            testsuite/emscripten-test-stuff/node-tests.sh

  test-node-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            testsuite/emscripten-test-stuff/node-tests.sh --enable-wasm-bigint

  test-selenium-firefox:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            pytest -k firefox testsuite/test_libffi.py

  test-selenium-chrome:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            pytest -k chrome testsuite/test_libffi.py

  test-selenium-firefox-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh --enable-wasm-bigint
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            export EXTRA_LDFLAGS="-s WASM_BIGINT=1"
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            pytest -k firefox testsuite/test_libffi.py

  test-selenium-chrome-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh --enable-wasm-bigint
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            export EXTRA_LDFLAGS="-s WASM_BIGINT=1"
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            pytest -k chrome testsuite/test_libffi.py

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-emsdk
      - test-node:
          requires:
            - install-emsdk
      - test-node-bigint:
          requires:
            - install-emsdk
      - test-selenium-firefox:
          requires:
            - install-emsdk
      - test-selenium-chrome:
          requires:
            - install-emsdk
      - test-selenium-firefox-bigint:
          requires:
            - install-emsdk
      - test-selenium-chrome-bigint:
          requires:
            - install-emsdk
