version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: hoodmane/pyodide-env:18
  environment:
    - EMSDK_NUM_CORES: 3
      EMCC_CORES: 3

jobs:
  # lint:
  #   <<: *defaults
  #   resource_class: small
  #   steps:
  #     - checkout

  #     - run:
  #         name: lint
  #         command: make lint


  install-emsdk:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install emsdk
          no_output_timeout: 1200
          command: |
            git clone https://github.com/emscripten-core/emsdk.git --depth=1
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest

      - persist_to_workspace:
          root: .
          paths:
            - .

  test-node:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            testsuite/emscripten-test-stuff/node-tests.sh

  test-node-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            testsuite/emscripten-test-stuff/node-tests.sh --enable-wasm-bigint


  # test-call:
  #   <<: *defaults
  #   steps:
  #     - checkout

  #     - run:
  #         name: build-test-call
  #         command: |
  #           cd testsuite
  #           cp -r libffi.call libffi.call.patched
  #           cd libffi.call.patched
            

  #     - run:
  #         name: run-test-call
            


  
  # test-closure:
  #   <<: *defaults
  #   steps:
  #     - checkout

  #     - run:
  #         name: 


workflows:
  version: 2
  build-and-test:
    jobs:
      - install-emsdk
      - test-node:
          requires:
            - install-emsdk
      - test-node-bigint:
          requires:
            - install-emsdk
