version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: pyodide/pyodide-env:20221102-chrome107-firefox106
  environment:
    - EMSDK_NUM_CORES: 3
      EMCC_CORES: 3

jobs:
  # lint:
  #   <<: *defaults
  #   resource_class: small
  #   steps:
  #     - checkout

  #     - run:
  #         name: lint
  #         command: make lint


  install-emsdk:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install emsdk
          no_output_timeout: 1200
          command: |
            git clone https://github.com/emscripten-core/emsdk.git --depth=1
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest

      - persist_to_workspace:
          root: .
          paths:
            - emsdk

  build-libffi:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: install autoconf 2.71
          command: |
            wget https://mirrors.sarata.com/gnu/autoconf/autoconf-2.71.tar.xz
            tar -xf autoconf-2.71.tar.xz
            cd autoconf-2.71
            ./configure
            make install
            cp /usr/local/bin/autoconf /usr/bin/autoconf

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh

      - run:
          name: build tests
          command: |
            source ./emsdk/emsdk_env.sh
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - persist_to_workspace:
          root: .
          paths:
            - target
            - testsuite

  build-libffi-bigint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: install autoconf 2.71
          command: |
            wget https://mirrors.sarata.com/gnu/autoconf/autoconf-2.71.tar.xz
            tar -xf autoconf-2.71.tar.xz
            cd autoconf-2.71
            ./configure
            make install
            cp /usr/local/bin/autoconf /usr/bin/autoconf

      - run:
          name: build
          command: |
            source ./emsdk/emsdk_env.sh
            ./build.sh --enable-wasm-bigint

      - run:
          name: build tests
          command: |
            source ./emsdk/emsdk_env.sh
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            export EXTRA_LD_FLAGS="-s WASM_BIGINT"
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test

      - persist_to_workspace:
          root: .
          paths:
            - target
            - testsuite

  test-firefox:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-chrome:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            pytest --junitxml=test-results/junit.xml -k chrome testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-firefox-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-chrome-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k chrome testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-node:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: install autoconf 2.71
          command: |
            wget https://mirrors.sarata.com/gnu/autoconf/autoconf-2.71.tar.xz
            tar -xf autoconf-2.71.tar.xz
            cd autoconf-2.71
            ./configure
            make install
            cp /usr/local/bin/autoconf /usr/bin/autoconf

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            rm testsuite/libffi.go/go.exp
            testsuite/emscripten-test-stuff/node-tests.sh

  test-node-bigint:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: install autoconf 2.71
          command: |
            wget https://mirrors.sarata.com/gnu/autoconf/autoconf-2.71.tar.xz
            tar -xf autoconf-2.71.tar.xz
            cd autoconf-2.71
            ./configure
            make install
            cp /usr/local/bin/autoconf /usr/bin/autoconf

      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            source ./emsdk/emsdk_env.sh
            rm testsuite/libffi.go/go.exp
            testsuite/emscripten-test-stuff/node-tests.sh --enable-wasm-bigint

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-emsdk

      - build-libffi:
          requires:
            - install-emsdk
      - build-libffi-bigint:
          requires:
            - install-emsdk

      - test-firefox:
          requires:
            - build-libffi
      - test-chrome:
          requires:
            - build-libffi

      - test-firefox-bigint:
          requires:
            - build-libffi-bigint
      - test-chrome-bigint:
          requires:
            - build-libffi-bigint

      - test-node:
          requires:
            - install-emsdk
      - test-node-bigint:
          requires:
            - install-emsdk
